### ISSUE TITLE
关于ae智能样板优化

### ISSUE THREAD

**Issue by Cori885** [SafariXiu/EyeOfHarmonyBuffer#22]
能不能做到，我下单114514的锭，但是我样板是1出1，他发配就按114514出114514发配，有没有可能作出这种功能

**Comment by SafariXiu** [comment]
？你这功能疑似有点怪了 原版也能做到吧 伪合成

**Comment by SafariXiu** [comment]
这种功能级别我做不到 除非你去官方发issue了
