### ISSUE TITLE
关于270版本该mod有关EOH相关的BUG

### ISSUE THREAD

**Issue by maple-9945** [SafariXiu/EyeOfHarmonyBuffer#42]
ME存储输入总线可以无限刷星阵（星阵还在AE里，但是可用剪线钳从EOH主机里取出星阵），加入星阵之后机器无法工作（原因待定，也可能不是该MOD的原因）
![image](https://github.com/user-attachments/assets/f4a468d8-6280-4e1a-8136-afa13390c498)

**Comment by SafariXiu** [comment]
确实 其实最主要的原因还是这东西本身就不支持 我写也只是改了他结构的部分 我需要再仔细研读一下代码才能确定能不能修 如果不行这个功能可能要删除

**Comment by SafariXiu** [comment]
好吧 EOH本身没有这个的处理逻辑 导致这玩意兼容后全是BUG 我需要暂时关闭这个功能了 可能会修好也有可能一辈子也搞不定
