### ISSUE TITLE
关于神锻模块的修改

### ISSUE THREAD

**Issue by maple-9945** [SafariXiu/EyeOfHarmonyBuffer#46]
![image](https://github.com/user-attachments/assets/3d7051ed-e434-430f-9988-65600e65c550)
修改后诸神之锻炉太阳聚变异化器模块无法成型，该截图机器在更新前是已成型的，更新后无法成型

**Comment by SafariXiu** [comment]
神锻那边的毛病 神锻重新开机试试 我这边测试过了没问题

**Comment by SafariXiu** [comment]
我没动检测方面的代码

**Comment by SafariXiu** [comment]
而且这东西很大 你最好确保所有机器区块都被加载到了 要不然就会卡结构加载 把后面那堆圆环也全加上
