### ISSUE TITLE
靶仓问题

### ISSUE THREAD

**Issue by maple-9945** [SafariXiu/EyeOfHarmonyBuffer#56]
输入512份材料也会一次消耗掉，产出量与输入一份材料产出一致，望修复。（最好顺便允许这玩意使用总成）

**Comment by Archintone** [comment]
我遇到的问题是：每次运行无论处理多少份材料，输出都是配方的256倍（跟cfg调的并行数量256一致）

**Comment by SafariXiu** [comment]
已修复
